version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

  test:
    build:
      context: .
      dockerfile: tech-db-forum.Dockerfile
    links:
      - app
    volumes:
      - ./reports:/reports
    command: sh -c "sleep 15 && tech-db-forum func -u http://app:5000/api -r /reposts/report.html"
